apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
  environment: {{ .Values.environment }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label }}
       # environment: {{ .Values.environment }} 
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.externalSecret.name }}  
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: 80
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: 80
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
{{- if .Values.secrets.useKeyVault }}
            - name: VAULT_KV_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.k8sSecretName }}
                  key: someSecretKey
{{- end }}
{{- end }}